// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:gpk_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BranchAdapter());
    registerAdapter(DayAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(EventGroupAdapter());
    registerAdapter(RoutineScheduleAdapter());
    registerAdapter(TimelineItemAdapter());
    registerAdapter(UserPreferencesAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BranchAdapter());
    registerAdapter(DayAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(EventGroupAdapter());
    registerAdapter(RoutineScheduleAdapter());
    registerAdapter(TimelineItemAdapter());
    registerAdapter(UserPreferencesAdapter());
  }
}
